### PR TITLE
Update # finance culculator.py

### PR DESCRIPTION
**Pull request by Waseem-Ahmad-Ebrahim**
Reviewing your code

### CODE REVIEW

**Comment by nkateko75** [comment]
Noted thanks

**Comment by Waseem-Ahmad-Ebrahim** [comment]
Please add error handling to your code so that when the user enters an incorrect data type, it does not break your program. Also update your readme to be more descriptive and include screenshots of the application in action.

**Review by Waseem-Ahmad-Ebrahim — COMMENTED** [review]
Add error handling

**Comment by nkateko75** [comment]
Noted, Thanks I will work on it.

**Review by nkateko75 — APPROVED** [review]

**Pull request merged**
